// <auto-generated />
using System;
using FlightWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightWebApi.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20231113022658_Dbupdate2")]
    partial class Dbupdate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightWebApi.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("FlightWebApi.Models.FlightDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdFlight")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<double>("Version")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdFlight");

                    b.HasIndex("TypeId")
                        .IsUnique();

                    b.ToTable("FlightsDocument");
                });

            modelBuilder.Entity("FlightWebApi.Models.FlightModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointOfLoading")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointOfUnloading")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightWebApi.Models.GroupPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FlightDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightDocumentId");

                    b.ToTable("GroupPermission");
                });

            modelBuilder.Entity("FlightWebApi.Models.Permisson", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("GroupPermissionId")
                        .HasColumnType("int");

                    b.Property<bool>("NoPermission")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReadAndModify")
                        .HasColumnType("bit");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("GroupPermissionId")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("FlightWebApi.Models.FlightDocument", b =>
                {
                    b.HasOne("FlightWebApi.Models.FlightModels", "FlightModels")
                        .WithMany("FlightDocuments")
                        .HasForeignKey("IdFlight")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightWebApi.Models.DocumentType", "DocumentTypes")
                        .WithOne("Documents")
                        .HasForeignKey("FlightWebApi.Models.FlightDocument", "TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentTypes");

                    b.Navigation("FlightModels");
                });

            modelBuilder.Entity("FlightWebApi.Models.GroupPermission", b =>
                {
                    b.HasOne("FlightWebApi.Models.FlightDocument", null)
                        .WithMany("GroupPermission")
                        .HasForeignKey("FlightDocumentId");
                });

            modelBuilder.Entity("FlightWebApi.Models.Permisson", b =>
                {
                    b.HasOne("FlightWebApi.Models.GroupPermission", "GroupPermission")
                        .WithOne("Permisson")
                        .HasForeignKey("FlightWebApi.Models.Permisson", "GroupPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightWebApi.Models.DocumentType", "DocumentType")
                        .WithMany("permissons")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("GroupPermission");
                });

            modelBuilder.Entity("FlightWebApi.Models.DocumentType", b =>
                {
                    b.Navigation("Documents")
                        .IsRequired();

                    b.Navigation("permissons");
                });

            modelBuilder.Entity("FlightWebApi.Models.FlightDocument", b =>
                {
                    b.Navigation("GroupPermission");
                });

            modelBuilder.Entity("FlightWebApi.Models.FlightModels", b =>
                {
                    b.Navigation("FlightDocuments");
                });

            modelBuilder.Entity("FlightWebApi.Models.GroupPermission", b =>
                {
                    b.Navigation("Permisson")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
